// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "techschool.pcbook.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "techschool.pcbook.LoginResponse")
}

func init() {
	proto.RegisterFile("auth_service.proto", fileDescriptor_0f39bb026ca10b68)
}

var fileDescriptor_0f39bb026ca10b68 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x18, 0x84, 0x95, 0x0a, 0x10, 0xb8, 0x05, 0x09, 0xb3, 0x94, 0x08, 0xa9, 0x25, 0x13, 0x30, 0xd8,
	0xa2, 0x6c, 0x30, 0xc1, 0xc0, 0xc4, 0x80, 0x0a, 0x13, 0x4b, 0x65, 0x9b, 0x5f, 0x89, 0xd5, 0xd4,
	0xbf, 0x89, 0xff, 0x94, 0x9d, 0x57, 0xe0, 0xd1, 0x78, 0x05, 0x1e, 0x84, 0xa4, 0x0e, 0x08, 0x09,
	0x3a, 0xde, 0x9d, 0xfd, 0xd9, 0x77, 0x8c, 0xab, 0x9a, 0x8a, 0x59, 0x80, 0x6a, 0x69, 0x0d, 0x08,
	0x5f, 0x21, 0x21, 0xdf, 0x27, 0x30, 0x45, 0x30, 0x05, 0x62, 0x29, 0xbc, 0xd1, 0x88, 0xf3, 0xf4,
	0x28, 0x47, 0xcc, 0x4b, 0x90, 0xca, 0x5b, 0xa9, 0x9c, 0x43, 0x52, 0x64, 0xd1, 0x85, 0x78, 0x21,
	0xbb, 0x65, 0x83, 0x3b, 0xcc, 0xad, 0x9b, 0xc2, 0x4b, 0x0d, 0x81, 0x78, 0xca, 0xb6, 0xeb, 0x06,
	0xe9, 0xd4, 0x02, 0x86, 0xc9, 0x38, 0x39, 0xd9, 0x99, 0xfe, 0xe8, 0x36, 0xf3, 0x2a, 0x84, 0x57,
	0xac, 0x9e, 0x87, 0xbd, 0x98, 0x7d, 0xeb, 0x6c, 0xc2, 0x76, 0x3b, 0x4e, 0xf0, 0x0d, 0x1d, 0xf8,
	0x31, 0x1b, 0x28, 0x63, 0x20, 0x84, 0x19, 0xe1, 0x1c, 0x5c, 0x07, 0xeb, 0x47, 0xef, 0xb1, 0xb5,
	0x26, 0xc4, 0xfa, 0xd7, 0x4d, 0x85, 0x87, 0xd8, 0x80, 0x03, 0xdb, 0x5c, 0x21, 0xf8, 0x48, 0xfc,
	0x69, 0x21, 0x7e, 0x7f, 0x32, 0x1d, 0xaf, 0x3f, 0x10, 0x5f, 0xcf, 0x0e, 0xdf, 0x3e, 0x3e, 0xdf,
	0x7b, 0x07, 0xd9, 0x9e, 0x5c, 0x9e, 0xcb, 0x76, 0x27, 0x59, 0xb6, 0xf9, 0x65, 0x72, 0x76, 0x73,
	0xca, 0x46, 0x06, 0x17, 0x22, 0xb7, 0x54, 0x2a, 0xfd, 0x0f, 0xc8, 0xeb, 0xfb, 0xe4, 0x69, 0x43,
	0x5c, 0x79, 0xad, 0xb7, 0x56, 0x1b, 0x5d, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x41, 0x03,
	0x2d, 0x6a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/techschool.pcbook.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/techschool.pcbook.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "techschool.pcbook.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_service.proto",
}
